### ISSUE TITLE
error in view for domain name

### ISSUE THREAD

**Issue by sebdraven** [PassiveDNS/PassiveDNS#14]
a bug in the view domain to print the good information: 

![image](https://user-images.githubusercontent.com/1478484/131699119-c1f7bb54-9ef2-4222-a032-37dd20962c41.png)

**Comment by sebdraven** [comment]
The bug is still here

![image](https://user-images.githubusercontent.com/1478484/132347651-38614e62-a798-4ff1-9811-01816c207737.png)


the information of record DNS  don't change

**Comment by Dadard29** [comment]
Should apply at next update
