### ISSUE TITLE
docker-compose build fails

### ISSUE THREAD

**Issue by mo8Zomo0** [PassiveDNS/PassiveDNS#23]
# docker -v
Docker version 20.10.9, build c2ea9bc
# docker-compose -v
docker-compose version 1.29.2, build 5becea4c
# cat /etc/issue
Debian GNU/Linux 10 \n \l

/opt/PassiveDNS# git log -1
commit 9769b57816189213bcc3aa09a7115c10bfe66667 (HEAD -> master, origin/master, origin/HEAD)
Merge: d1ba9b9 a13a583

/opt/PassiveDNS# docker-compose build
api uses an image, skipping
scheduler uses an image, skipping
Building db
Sending build context to Docker daemon  10.75kB
Step 1/2 : FROM arangodb:latest
latest: Pulling from library/arangodb
e519532ddf75: Already exists 
18189da276de: Pull complete 
127d4d251d2e: Pull complete 
556484d115dd: Pull complete 
Digest: sha256:76c320350a8e3734ab680745f40b29b25533f19b0f44cb4bcecf4cbbcd55ea93
Status: Downloaded newer image for arangodb:latest
 ---> 769f7293da46
Step 2/2 : COPY _init_db_tmp.js /docker-entrypoint-initdb.d/
 ---> 3eab4314c203
Successfully built 3eab4314c203
Successfully tagged passivedns_db:latest
Building front
Sending build context to Docker daemon  1.806MB
Step 1/12 : FROM node:latest as build-stage
latest: Pulling from library/node
bb7d5a84853b: Already exists 
f02b617c6a8c: Pull complete 
d32e17419b7e: Pull complete 
c9d2d81226a4: Pull complete 
3c24ae8b6604: Pull complete 
a7c459a8e2ce: Pull complete 
6907b68f1eec: Pull complete 
67ca14c3c53c: Pull complete 
7e250bc43b70: Pull complete 
Digest: sha256:fb256ef025424b407fb806a9828b105d82aac93c7168a1a8bc156bc82996b939
Status: Downloaded newer image for node:latest
 ---> 803ad17a604b
Step 2/12 : ARG HOST=http://localhost:8080
 ---> Running in fd6aead82979
Removing intermediate container fd6aead82979
 ---> b682461d1e79
Step 3/12 : WORKDIR /app
 ---> Running in fc11fa51cbf4
Removing intermediate container fc11fa51cbf4
 ---> 6c30746db6b1
Step 4/12 : COPY package*.json ./
 ---> 959fd7bc5033
Step 5/12 : RUN npm install
 ---> Running in 9e813ec6ebb2
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.

added 1297 packages, and audited 1298 packages in 40s

5 packages are looking for funding
  run `npm fund` for details

46 vulnerabilities (18 moderate, 28 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice 
npm notice New patch version of npm available! 8.1.2 -> 8.1.3
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.1.3>
npm notice Run `npm install -g npm@8.1.3` to update!
npm notice 
Removing intermediate container 9e813ec6ebb2
 ---> e90d16890a1e
Step 6/12 : COPY ./ .
 ---> 3d2b45e4c65f
Step 7/12 : RUN sed -i -e "s+{{HOST}}+$HOST+g" "./src/services/config.json"
 ---> Running in 377ed389967b
Removing intermediate container 377ed389967b
 ---> aba44fc7f4b6
Step 8/12 : RUN npm run build
 ---> Running in e9c9e1767ad9

> pfa_gui@0.1.0 build
> vue-cli-service build

-  Building for production...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /app/node_modules/webpack/lib/NormalModule.js:503:5
    at /app/node_modules/webpack/lib/NormalModule.js:358:12
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/app/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/app/node_modules/loader-runner/lib/LoaderRunner.js:114
			throw e;
			^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /app/node_modules/webpack/lib/NormalModule.js:503:5
    at /app/node_modules/webpack/lib/NormalModule.js:358:12
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /app/node_modules/cache-loader/dist/index.js:147:7
    at /app/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:188:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0
The command '/bin/sh -c npm run build' returned a non-zero code: 1
ERROR: Service 'front' failed to build : Build failed

**Comment by sebdraven** [comment]
Hi, 

you can add in package.json 

in entry scripts openssl option like this

 "scripts": {
    "serve": "vue-cli-service --openssl-legacy-provider --port 8081",
    "build": "vue-cli-service --openssl-legacy-provider build",
    "build-demo": "vue-cli-service --openssl-legacy-provider build --mode demo",
    "lint": "vue-cli-service --openssl-legacy-provider lint"
  },

**Comment by sebdraven** [comment]
I found the root problem, it's the version of node. 

In Dockerfile of front the version of node.js: 

FROM node:16.10.0 as build-stage

and the build is Ok
