### ISSUE TITLE
There seems to be a 'hostname' issue when you run the Docker images

### ISSUE THREAD

**Issue by swedishmike** [PassiveDNS/PassiveDNS#4]
If I do a `docker-compose up` there are issues with the connectivity between the different images.

(Part of) one error that pops up is as follows:

`api_1        | requests.exceptions.ConnectionError: HTTPConnectionPool(host='db', port=8529): Max retries exceeded with url: /_db/passive_dns/_api/cursor (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f10915a8100>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

It looks like it wants a host named db but the hostname that's generated when you `docker-compose up` it is `db_1`.

I'll see if I can find where the connection string is, but might be quicker done by someone who knows the project better?

**Comment by sebdraven** [comment]
you have launch the db.py like the documentation ?

**Comment by swedishmike** [comment]
I've just run `docker-compose up` and was expecting that to run stuff for me so to speak?

**Comment by sebdraven** [comment]
Read the documentation it's good ;) https://github.com/PassiveDNS/PassiveDNS/wiki/Docker-Installation

**Comment by swedishmike** [comment]
My bad. Assumed to much. Will try the init scripts now. ;)

Thanks for pointing me in the right direction!
