### ISSUE TITLE
Suggest timezone settings

### ISSUE THREAD

**Issue by udgover** [PassiveDNS/PassiveDNS#7]
Hi,

First of all, thanks for this nice project!

Just a minor issue to share with you. As shown in below example, domain was added few seconds before screenshoting. However, last IP change is already set to "2 hours ago"

![last_ip_change_utc](https://user-images.githubusercontent.com/1006203/125815816-9a871001-7a4d-4c50-a6d4-fe74da677f6b.png)

Suggestions: 

- Ability to set timezone (via config, env vars, ...) to get accurate timestamps both in views and API
- or highlight this behavior in documentation.
- or add ISO timestamps in view (with tz information, UTC here)

Keep up the good work!

**Comment by Dadard29** [comment]
Hi,

Thanks for the feedback !

I opened the PR #8 in order to solve this issue.

I will update the docs as soon as it is merged.
